### ISSUE TITLE
Remove 'npm' dependency

### ISSUE THREAD

**Issue by yinzara** [semantic-release/npm#272] opened 2020-08-31 22:01 UTC
The 'npm' dependency on this project does not seem to be used. I can find no reference to a "require('npm')" anywhere in the project or anything related to it.  

Even if it was the case, why is it listed in "dependencies" and not in "peerDependencies"?

Because of this, any install that includes @semantic-release/npm includes an 8mb download and extraction just for the "npm" package.

Can this just be removed or at least changed to a peerDependency?

**Comment by gr2m** [comment] 2020-08-31 22:23
we use the npm binary using `execa`. Moving it to `peerDependencies` would not solve the problem, you would still need to have it installed, and peerDependencies will be installed by default (again) with the upcoming npm 7.

We are considering a `semantic-release` core package without the built-in plugins though, so if you don't use `npm` you won't need to install this plugin

**Closed by gr2m** 2020-08-31 22:23 UTC
Labels: support

**Comment by yinzara** [comment] 2020-09-01 06:14
There is a very serious difference between a peerDependency and a normal dependency especially when it comes to `npm` itself.  NPM is not a package normally added to a library. It's something installed at the system level with NodeJS.  By making "npm" a dependency of this library, you make someone download more than 10MB of a dependency that they normally would not need and also tie that user to a specific version of NPM.  You can still use `execa` and execute the npm available at the system path.  You do not need to force the user to install npm yet again.  Every single person who is running this plugin already has npm installed because they have NodeJS installed.   

Additionally, while you may say "it doesn't matter for npm 7", you are assuming someone depending on this library is using "npm" as their package manager when they could just as easily be using yarn or pnpm.  I may still want to use this plugin to manage the version of my package.json file and publish to the npmjs registry even though I use another package manager.

Please remove the `npm` dependency or at least make it a peerDependency.  

It's absolutely unnecessary.

**Comment by travi** [comment] 2020-09-01 13:52
@yinzara your question was answered above. getting more aggressive and asserting that the reasoning from a maintainer about why the project uses a dependency is an inappropriate way to interact with any maintainer, especially those of us doing this work on our own time for free.

this package has a very direct dependency on npm for the publishing process. being able to ensure that the version used is the one that has been tested to work with the corresponding version of this package is an intentional decision to avoid misconfigurations that can be common across the large number of users of this tool. while it may not be common for tools that only execute in the context of npm to install npm as a dependency, it is a valid approach and much more valuable in cases like this where there is actually a direct dependency.

if the size if the dependency is unacceptable to you, you have options. for example, rather than installing semantic-release as a local dependency, i prefer to use npx so that it is only downloaded on ci when actually being executed rather than being required on developers machines. if the available options are still unacceptable to you, you are welcome to use another tool, but making demands, as you have, is inappropriate and will not work to convince maintainers that have valid reasons for the decisions that have been made.

**Comment by mikecbrant** [comment] 2020-09-04 01:12
I will add in here that we are seeing unexpected behavior in our repos that we believe are related to having this dependency installed and potentially overriding global npm execution of npm scripts.

I our case as soon as we changed from semantic-release/npm@beta version 6 to regular version six release (with npm 7 dependency, we start having cases where npm installs are not installing  our dependency executable to top level `node_module/.bin/` directory.  When we pinned our dependency back to the beta version (with npm 6 dependency), this issue went away.

Now I honestly can't say this was the root cause, but having this package installed locally for a repo just make thinkgs confusing for developers.

On the beta 6 version, for example I know my npm scripts are being run by local npm because I get prompted to upgrade npm (when my global install had already been updated). 

Having this npm dependency installed just seems problematic, especially when you are installing major version upgrades beyond what global npm versions are installed like happened here with version 6 release.
