### ISSUE TITLE
Support for version bumping in multiple package.json files.

### ISSUE THREAD

**Issue by EvanCarroll** [semantic-release/npm#379] opened 2021-07-30 19:30 UTC
This feature is needed to properly support [Angular Libraries](https://angular.io/guide/libraries).

Currently `@semantic-release/npm` supports bumping a version in `package.json` in one location. But this is not sufficient for an  Angular Library, which has

* One `package.json` for the library (project) in the workspace
* And, another `package.json` for the library in `./dist` as a result of `ng build` which must be run **before** the `semantic-release`

Some advice on this forum says as a workaround, you should clobber the `package.json` in the source with the copy in `dist`. But this is not a good solution because the built copy is likely to have files the production copy does **NOT** have.

Here is an example of content **ONLY** in the `package.json` produced by `ng build`:

```text
  "main": "bundles/cpanel-angular-validators.umd.js",
  "module": "fesm2015/cpanel-angular-validators.js",
  "es2015": "fesm2015/cpanel-angular-validators.js",
  "esm2015": "esm2015/cpanel-angular-validators.js",
  "fesm2015": "fesm2015/cpanel-angular-validators.js",
  "typings": "cpanel-angular-validators.d.ts",
  "metadata": "cpanel-angular-validators.metadata.json",
  "sideEffects": false
}
```

What is really needed is for `@semantic-release/npm` to be able to set sync versions multiple `package.json`'s versions.

Workaround
====

Assuming you,

*  have only one `package.json` file in `dist`
* only one in `projects` (which is the only supported method as monorepos are not supported) this script should work for keeping the who in sync.
* note, the implementation above would need none of these work arounds because it could know for certain both of these locations.

```sh
#!/bin/sh

#
# The @semantic-release/npm tool bumps the version number in one location only.
# If it bumps the location in the dist, we need to safely copy that into the
# source directory.
#

SRC=$(find ./projects -name package.json)
DIST=$(find ./dist -name package.json)
VERSION=$(jq .version "$DIST")

cat -e <<EOF
  Syncing version $VERSION
    DIST: $DIST
    SRC: $SRC
EOF

jq ".version = ${VERSION}" $SRC | sponge "$SRC"
```

Other Issues
====

* #64 could use this,
* #246 would not be a problem with this option

**Comment by gr2m** [comment] 2021-07-30 19:52
Would that approach work for you?

https://github.com/octokit/openapi-types.ts/blob/f414616822bf94b3ff13314e97ec192cb81d2050/package.json#L27-L61

You can configure `@semantic-release/npm` to run multiple times.

We are also considering to make the `pgkRoot` option accept a path pattern and/or a list of paths, which would make the workaround I linked uneccessary

**Comment by EvanCarroll** [comment] 2021-07-30 19:59
It's not ideal, I guess the question there is how do you designate that it should **ONLY** update the version number and not push to NPM or the repo? In my example, I only want the package to `dist` to fly to the repo. 

> We are also considering to make the pgkRoot option accept a path pattern and/or a list of paths, which would make the workaround I linked uneccessary

I guess we have two functions here we should consider for multiple paths,

* Pushing up each path to the repo,
* Merely bump the version in the package.json at each path.

I only want to bump the version number at each path, so if `pkgRoot` was an array paths that wouldn't satisfy the need either. I would need to be able to designate which path should be pushed from. Ideas?

**Comment by gr2m** [comment] 2021-07-30 20:57
the `@semantic-release/npm` plugin is not pushing anything, it's just updating files. In fact `semantic-release` doesn't push anything by default. If you want to push files back, I assume you use `semantic-release/git`? That's out of scope here

**Comment by EvanCarroll** [comment] 2021-07-30 21:00
@gr2m I mean `npm publish`.

**Comment by gr2m** [comment] 2021-07-30 21:01
you can use the npmPublish option: 
https://github.com/semantic-release/npm#options

**Comment by EvanCarroll** [comment] 2021-07-30 21:04
And you want to make `pkgRoot` an array. If you were to do that, how would you know which of the directories in the array `npmPublish` is to target.

**Comment by gr2m** [comment] 2021-07-30 21:07
all of them. If you need to publish some but not others then run the plugin multiple times as I suggested.

I'm going to close the issue because the workaround works for your use case and there is nothing actionable for us to do, but feel free to continue to comment if you have any other questions

**Closed by gr2m** 2021-07-30 21:07 UTC

**Comment by EvanCarroll** [comment] 2021-07-30 21:13
@gr2m Well, this is not a desirable workaround for the reasons given. But just to be clear, and as specified in the question, this isn't about making monorepos work (which is currently unsupported). This is about making vanilla angular projects without having to implement hacks in postversion hooks.

* A repo represents one project.
* A project represents one package to be published.
* A project builds into `dist/` before semantic-release is run.
* The package is created from `dist/`
* The pkgRoot should presumably be `dist/`
* The code should have it's build number bumped too for future plugins like `@semantic-release/git`

**Comment by gr2m** [comment] 2021-07-30 21:38
The solution to run the `@semantic-release/npm` plugin twice does exactly what you need, doesn't it? It updates two package.json files, and you can set the order so that the first call doesn't publish, but the 2nd does. It's not a hack, it works as designed with the options available today. I feel like I miss something you need but I don't know what it is
