### ISSUE TITLE
Set scope access on first publish

### ISSUE THREAD

**Issue by mattyclarkson** [semantic-release/npm#46] opened 2018-01-24 16:51 UTC
When publishing to a scope, the first release can specify `--access public` to turn the package under that scope public. Currently I just hack in the argument on my first CI run. Would be good to figure out a way to do this automatically.

**Comment by pvdlg** [comment] 2018-01-24 17:04
Please see this [FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#how-can-i-set-the-access-level-of-the-published-npm-package).

It's also mentioned in [README.md#npm-configuration](https://github.com/semantic-release/npm#npm-configuration) that npm configuration can be set via `.npmrc` and `publishConfig`.

**Comment by pvdlg** [comment] 2018-01-24 17:04
Duplicate of #33

**Closed by pvdlg** 2018-01-24 17:04 UTC
Labels: support
