### ISSUE TITLE
feature: publish more then one npm package

### ISSUE THREAD

**Issue by dvabuzyarov** [semantic-release/npm#261] opened 2020-03-26 20:24 UTC
I have a monorepo with 2 packages. The first one is production package and the second is a code generation at the design time package. The second package is always locked on the first one. 
I would like to publish 2 packages at once with the same versions.

what if the option pigroot will accept an array of strings?
``` typescript 
"pkgRoot": ["dist/ng-grpc", "dist/protoc-gen"]
```

**Comment by pvdlg** [comment] 2020-03-27 04:13
Monorepo are not supported at this time. Please see #193.

**Comment by pvdlg** [comment] 2020-03-27 04:14
Duplicate of #193

**Closed by pvdlg** 2020-03-27 04:14 UTC
