### ISSUE TITLE
NPM publish: SemanticReleaseError: Invalid npm token.

### ISSUE THREAD

**Issue by varnastadeus** [semantic-release/npm#215] opened 2019-11-01 14:21 UTC
## Current behavior

Can't publish with valid token using semantic-release. Running from local machine in dry run mode using:  
`GH_TOKEN=*** NPM_TOKEN=*** npx semantic-release`.

Running `npm publish` with the same token works as expected.  
npm version: `6.11.3`
node version: `v12.12.0`

## Expected behavior

Semantic-release should be able to publish to npm successfully.
## Environment

- **semantic-release** version: 15.13.27
- CI environment: github actions
- Plugins used: 
```
"@semantic-release/commit-analyzer",
"@semantic-release/changelog",
"@semantic-release/github
"@semantic-release/npm",
@semantic-release/release-notes-generator
```
- **semantic-release** configuration: 
```
"release": {
    "branch": "master",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/changelog",
      "@semantic-release/github",
      [
        "@semantic-release/npm",
        {
          "pkgRoot": "dist/ng-select"
        }
      ],
      "@semantic-release/release-notes-generator"
    ]
  }
```

- Logs running in dry mode on local machine:
```
[4:12:33 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.27
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:12:33 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:12:33 PM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[4:12:33 PM] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[4:12:37 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:12:37 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[4:12:37 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[4:12:37 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[4:12:37 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[4:12:37 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[4:12:37 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:12:37 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
https://registry.npmjs.org/
Error: Command failed with exit code 1 (EPERM): npm whoami --registry https://registry.npmjs.org/
    at makeError (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/lib/verify-auth.js:20:7)
    at async verifyConditions (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/index.js:33:7)
    at async validator (/Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as verifyConditions] (/Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/Users/tadeus/git/ng-select/node_modules/semantic-release/index.js:84:3) {
  command: 'npm whoami --registry https://registry.npmjs.org/',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'npm ERR! cb() never called!\n' +
    '\n' +
    'npm ERR! This is an error with npm itself. Please report this error at:\n' +
    'npm ERR!     <https://npm.community>\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/tadeus/.npm/_logs/2019-11-01T14_12_39_078Z-debug.log',
  all: 'npm ERR! cb() never called!\n' +
    '\n' +
    'npm ERR! This is an error with npm itself. Please report this error at:\n' +
    'npm ERR!     <https://npm.community>\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/tadeus/.npm/_logs/2019-11-01T14_12_39_078Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
[4:12:39 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[4:12:39 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[4:12:39 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token configured in the NPM_TOKEN environment variable must be a valid token allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

AggregateError:
    SemanticReleaseError: Invalid npm token.
        at module.exports (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/Users/tadeus/git/ng-select/node_modules/@semantic-release/npm/lib/verify-auth.js:23:33)
    at /Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/Users/tadeus/git/ng-select/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/Users/tadeus/git/ng-select/node_modules/semantic-release/index.js:84:3)
    at async module.exports (/Users/tadeus/git/ng-select/node_modules/semantic-release/index.js:170:22)
    at async module.exports (/Users/tadeus/git/ng-select/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}%
```

**Comment by pvdlg** [comment] 2019-11-01 15:28
The `@semantic-release/npm` plugin check first if you have a `./.npmrc` or a `~/.npmrc` file with an an auth token, and you do it uses that one instead of the `NPM_TOKEN` environment variable.

Do you have either a `./.npmrc` or a `~/.npmrc` file in the environment that runs semantic-release? Please make sure you don't have an outdated token there.

**Comment by varnastadeus** [comment] 2019-11-01 18:37
@pvdlg I am using exactly same token as in `~/.npmrc` and I am getting this error.
Running plain `npm publish` works as expected.

**Comment by pvdlg** [comment] 2019-11-01 21:03
What do you get when you run `npm whoami --registry https://registry.npmjs.org/`.

What do you have exactly in your `.npmrc` (you can replace the actual token by XXXX, but I'd like to see how it's defined)?

**Comment by varnastadeus** [comment] 2019-11-01 21:07
```
~ » npm whoami --registry https://registry.npmjs.org/
varnastadeus
--------------------------------------------------------------------------------
~ » cat ~/.npmrc                                     
//registry.npmjs.org/:_authToken=***
-------------------------------------------------------------------------------
```

**Comment by pvdlg** [comment] 2019-11-01 21:15
As you can see from the logs the command `npm whoami --registry https://registry.npmjs.org/` fails...Are you sure this is the `~/.npmrc` you have on the environment where you are running semantic-release (probably your CI)?

**Comment by varnastadeus** [comment] 2019-11-01 21:19
I am getting this error both on local machine and CI

**Comment by pvdlg** [comment] 2019-11-01 21:21
What version of `@semantic-release/npm` do you have in your `node_modules` directory?

**Comment by varnastadeus** [comment] 2019-11-01 21:23
it is 5.2.0

**Comment by pvdlg** [comment] 2019-11-01 21:28
In 5.2.0 the `~/.npmrc` was ignored and only the `./.npmrc` was used.
So the only explanation I see is that you must have a `./.npmrc` with a wrong token.

**Comment by varnastadeus** [comment] 2019-11-02 08:44
I can confirm that there is no `./.npmrc` also using the latest version results is same error :/

**Comment by pvdlg** [comment] 2019-11-02 19:26
Can you run it again with version 5.3.3 and provide the full logs? Thanks

**Comment by varnastadeus** [comment] 2019-11-02 21:24
```
```

**Comment by streamich** [comment] 2019-11-02 21:35
Having the same problem, all my projects fail with `EINVALIDTOKEN`, although token is valid.

Example: https://circleci.com/gh/streamich/react-use/1819?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by xobotyi** [comment] 2019-11-02 23:17
Suppose there is an issue related to execa, but to investigate it the caught error has to be unsuppressed: https://github.com/semantic-release/npm/blob/a0120d20e84924d076e5bb1ee451d8307e7db023/lib/verify-auth.js#L20

**Comment by xobotyi** [comment] 2019-11-03 05:55
@pvdlg forked and altered the package in package to add some debug points.
The problem with `execa`:
```
5:52:47 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[5:52:47 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[5:52:47 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[5:52:47 AM] [semantic-release] [@semantic-release/npm] › ℹ  Modified @semantic-release/npm version for sake of debug
[5:52:47 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[5:52:47 AM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/4835f98981b2182d778ee384d1ff3790/.npmrc
[5:52:47 AM] [semantic-release] [@semantic-release/npm] › ℹ  /tmp/4835f98981b2182d778ee384d1ff3790/.npmrc: '//registry.npmjs.org/:_authToken = ${NPM_TOKEN}'
[5:52:48 AM] [semantic-release] [@semantic-release/npm] › ℹ  {
  command: 'npm whoami --userconfig /tmp/4835f98981b2182d778ee384d1ff3790/.npmrc --registry https://registry.npmjs.org/',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "npm ERR! Cannot read property 'objectMode' of undefined\n" +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /root/.npm/_logs/2019-11-03T05_52_48_062Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
[5:52:48 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[5:52:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[5:52:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[5:52:48 AM] [semantic-release] › ✖  An error occurred while running semantic-release: AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/verify-auth.js:27:33)
    at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/verify-auth.js:27:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'AggregateError',
  pluginName: '@semantic-release/npm'
}
AggregateError: 
    AggregateError: 
        SemanticReleaseError: Invalid npm token.
            at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
            at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/verify-auth.js:27:33)
        at module.exports (/root/repo/node_modules/@semantic-release/npm/lib/verify-auth.js:27:13)
    at /root/repo/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/root/repo/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/root/repo/node_modules/semantic-release/index.js:84:3)
    at async module.exports (/root/repo/node_modules/semantic-release/index.js:170:22)
    at async module.exports (/root/repo/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1

**Comment by pvdlg** [comment] 2019-11-03 20:49
@varnastadeus the problem is that you have a `yarn.lock` file that forces an outdated version of `@semantic-release/npm` in which the `~/.npmrc` was ignored. So it would use the `NPM_TOKEN` variable which is probably set to an invalid token.
When you run `npm install` instead `yarn install` it would install the latest version of `@semantic-release/npm` which use your `~/.npmrc` that contains the correct token and ignore the `NPM_TOKEN` variable.

I would recommend to not use a `yarn.lock` if you have a library that you publish on npm to avoid having outdated dependencies. If you want to keep one you should update it frequently to avoid locking outdated dependencies and sub-dependencies.

**Comment by pvdlg** [comment] 2019-11-03 20:53
@xobotyi your issue seems to be unrelated to the one experienced by @varnastadeus.

The error from your logs is `Cannot read property 'objectMode' of undefined`. There is nothing that indicate if the error come from `execa` or `npm` or one of the sub-dependencies. It also seems specific to your environment as it doesn't happen anywhere else (all the semantic-release repo use semantic-release to release and this command work as expected.)

I would recommend to log the stacktrace so you can figure out where exactly the `Cannot read property 'objectMode' of undefined` error happen and why it happens. When you find out you can open an issue in the project where the error happens describing what in your particular setup create that.

**Comment by xobotyi** [comment] 2019-11-04 09:20
@pvdlg well, you're right.
After re-creating the `yarn.lock` everything came back to normal.

**Comment by pvdlg** [comment] 2019-11-04 15:27
I'm going to close this issue then

**Closed by pvdlg** 2019-11-04 15:27 UTC
Labels: info requested, plugin:npm

**Comment by varnastadeus** [comment] 2019-11-04 16:54
> So it would use the `NPM_TOKEN` variable which is probably set to an invalid token.

In my case I was using the same token as in `~/.npmrc`, not sure how it could get invalid token. Anyway, I am using `npm install` in my CI and it works fine.

**Comment by pvdlg** [comment] 2019-11-04 17:26
Maybe you had an outdate version with another bug due to your lockfile that is fixed now.

**Comment by prokopsimek** [comment] 2020-01-15 11:02
The same issue with v6 and recreating the lockfile helped. Thanks.

**Comment by grantila** [comment] 2020-11-21 13:13
I'm getting this for GitHub Actions with `npx semantic-release` and I don't have a `yarn.lock` or `package-lock.json`.

**Comment by grantila** [comment] 2020-11-21 14:14
From command line on my local machine, a "publish" token works, but "automation" tokens don't. And I can't use "publish" tokens in CI/CD because they require 2FA.
This seems like a serious bug (unless it's something on the npmjs.org side being temporarily broken)

**Comment by grantila** [comment] 2020-11-22 08:35
I see now that what I'm experiencing is already reported in #277 so never mind this.
