### ISSUE TITLE
Bump npm dependency version to at least 6.6.0 (WARN deprecated socks@1.1.10)

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [semantic-release/npm#141] opened 2019-02-08 15:21 UTC
Hi!

I'm using the latest version of `semantic-release` and upon running npm install I get the following warning:

`npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0`

According to `npm list socks` I get the following tree of dependencies:

```
my-project
└─┬ semantic-release@15.13.3
  └─┬ @semantic-release/npm@5.1.4
    └─┬ npm@6.5.0
      ├─┬ npm-profile@3.0.2
      │ └─┬ make-fetch-happen@4.0.1
      │   └─┬ socks-proxy-agent@4.0.1
      │     └── socks@2.2.0 
      └─┬ npm-registry-fetch@1.1.0
        └─┬ make-fetch-happen@3.0.0
          └─┬ socks-proxy-agent@3.0.1
            └── socks@1.1.10 
```

After a bit of research I found a commit for `npm/cli` which updates `npm-registry-fetch` to a version, which has `socks@2.x.x` among it's dependencies and that commit was released right after `npm@6.5.0` was released.

https://github.com/npm/cli/commit/9cefcdc1d2289b56f9164d14d7e499e115cfeaee#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Please bump the version of npm to at least 6.6.0 to get that warning fixed.

**Comment by pvdlg** [comment] 2019-02-11 20:33
Duplicate of #136

**Closed by pvdlg** 2019-02-11 20:33 UTC
